### PR TITLE
Feat/header

### PR DESCRIPTION
**Pull request by OysteinKoder**
header

### CODE REVIEW

**Comment by OysteinKoder** [comment]
Great work, make it responsive for mobile

**Comment by knutcode** [comment]
Header now responds to a 820px break-point. 

Code borrowed from [my own open-source portfolio](https://github.com/knutcode/portfolio)

**Comment by knutcode** [comment]
> Great work, make it responsive for mobile

Header now responds to a 820px break-point. 

Code borrowed from [my own open-source portfolio](https://github.com/knutcode/portfolio)

EDIT:

Due to change when the [Figma design](https://www.figma.com/file/36gZt0YkWI7BgNwLCtHycK/kodehode-side?node-id=1%3A98) eventually updates.

**Comment by OysteinKoder** [comment]
awsome

**Comment by OysteinKoder** [comment]
good job

**Pull request merged**
